### ISSUE TITLE
安装插件后似乎没有效果

### ISSUE THREAD

**Issue by KJZH001** [MuttonString/Furigana#1]
网易云版本 3.0.0.Beta (64位) (Build: 202125) Patch:81b191d

BetterNCM 1.3.2

插件版本0.1.1

![image](https://github.com/MuttonString/Furigana/assets/29683578/95cb0f74-3550-4c55-a96f-40769070947a)

![image](https://github.com/MuttonString/Furigana/assets/29683578/af93354b-5812-4016-bd96-8ac67582754c)

如图，假名没有被标注上去，重启过网易云很多次以确保外挂插件正确载入

插件设置保持为默认状态，没有额外修改

由于我不太清楚日志可以从哪里得到，所以这里目前没有附上日志

如果需要更多信息，请留言告诉我

**Comment by MuttonString** [comment]
不好意思，这个插件用的给汉字注音的在线API在一段时间前失效了。所以现在插件的最主要功能废了，只有更改字体之类的功能能用了。
下个版本把API换掉。大学期末考试在即，要过几周才能更新了（大概）
