### ISSUE TITLE
有关RefinedNowPlaying逐字歌词无法显示注音的问题

### ISSUE THREAD

**Issue by StarsWhere** [MuttonString/Furigana#3]
RefinedNowPlaying使用的逐字歌词源是另外的，可以 F12 Console 看到，是否对此还有适配兼容的打算？此外，谢谢你的项目，非常好用。

**Comment by MuttonString** [comment]
感谢你的反馈。
此项目**会**考虑适配兼容RefinedNowPlaying的逐字歌词。但由于RefinedNowPlaying的逐字歌词的实现方式是将每一个字都放进单独一个DOM元素中，故兼容工作相对需要更多时间，且对于超过一个汉字的单词，难以达到完美的视觉效果。

**Comment by MuttonString** [comment]
已于最新版本兼容RefinedNowPlaying的逐字歌词
