### ISSUE TITLE
获取时间过长

### ISSUE THREAD

**Issue by BPTPW** [MuttonString/Furigana#5]
每一次请求的获取时间在6s左右，是网络的问题还是性能的问题

**Comment by MuttonString** [comment]
获取时间取决于网络。不过请求获取确实不是很快，下个版本我争取换个快点的API试试罢

**Comment by BPTPW** [comment]
我代理开了关了都试过好像影响不是很大（最好可以搞个缓存？

**Comment by MuttonString** [comment]
没找到更快的API。在最新版本搞了个勉强能用的缓存
